### ISSUE TITLE
Trying to run gulp

### ISSUE THREAD

**Issue by jbello94** [mihailgaberov/es6-bingo-game#45]
E:\bingo-master\node_modules\gulp-jest\lib\index.js:29
    _jestCli2.default.runCLI(options, [options.rootDir]).then(function (_ref) {
                      ^

TypeError: Cannot read properties of undefined (reading 'runCLI')
    at DestroyableTransform._transform (E:\bingo-master\node_modules\gulp-jest\lib\index.js:29:23)
    at Transform._read (E:\bingo-master\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (E:\bingo-master\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (E:\bingo-master\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (E:\bingo-master\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Writable.write (E:\bingo-master\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (E:\bingo-master\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (node:events:513:28)
    at DestroyableTransform.emit (node:domain:552:15)
    at addChunk (E:\bingo-master\node_modules\readable-stream\lib\_stream_readable.js:291:12)

Node.js v18.8.0

**Comment by mihailgaberov** [comment]
Try with older Node.js version.

**Comment by jbello94** [comment]
how older?

**Comment by jbello94** [comment]
happened same with node v16.20.2, do you remember what version you used?

**Comment by mihailgaberov** [comment]
Probably 14x....

**Comment by mihailgaberov** [comment]
@jbello94 Did it work?

**Comment by jbello94** [comment]
> @jbello94 Did it work?

Nop 😕

**Comment by mihailgaberov** [comment]
Which versions of Node and npm have you tried with?
